name: Ctest
on:
  push:
  workflow_dispatch:
jobs:
  first:
    runs-on: ubuntu-latest
    env:
      test: dev
    steps:
      - name: Run a one-line script
        run: echo Hello!, $test
  second:
    needs:
      first
    runs-on: ubuntu-latest
    env:
      names: prod
    steps:
      - name: test second program
        run: |
          echo test
          echo $names
       

      
